// https://html.spec.whatwg.org/multipage/semantics.html#htmlanchorelement

[CustomElementCallbacks]
interface CustomHTMLAnchorElement : HTMLElement {
  [Reflect] attribute DOMString target;
  [Reflect] attribute DOMString download;
  [Reflect, PutForwards=value] attribute DOMSettableTokenList ping;
  [Reflect] attribute DOMString rel;
  [Reflect=rel] readonly attribute DOMTokenList relList;
  [Reflect] attribute DOMString hreflang;
  [Reflect] attribute DOMString type;

  attribute DOMString text;
};

CustomHTMLAnchorElement implements URLUtils;
